# Generated by Django 3.2.7 on 2021-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
