# Generated by Django 3.2.7 on 2021-09-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_donation_donationsmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donationsmanagement',
            name='donationType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIs.donation'),
        ),
    ]
