# Generated by Django 3.2.7 on 2021-09-30 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationsmanagement',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIs.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
