# Generated by Django 3.2.7 on 2021-10-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0005_auto_20210930_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
